apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
  namespace: default
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: 880252974759.dkr.ecr.us-east-1.amazonaws.com/winter-catalog-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "40m"
            memory: "80Mi"
          limits:
            cpu: "80m"
            memory: "150Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: catalog-service
