apiVersion: v1
kind: Secret
metadata:
  name: winter-core-secrets
  namespace: default
type: Opaque
stringData:
  MONGODB_URI: "REDACTED"
  SPRING_DATASOURCE_URL: "REDACTED"
  SPRING_DATASOURCE_USERNAME: "REDACTED"
  SPRING_DATASOURCE_PASSWORD: "REDACTED"
