name: Catalog Service CI/CD Pipeline

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/catalog-service/**'

jobs:
  build-and-deploy:
    name: Build & Deploy Catalog Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t 880252974759.dkr.ecr.us-east-1.amazonaws.com/winter-catalog-service:latest ./backend/catalog-service
          docker push 880252974759.dkr.ecr.us-east-1.amazonaws.com/winter-catalog-service:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name WinterClusterE1A7478C-5bf7dcc0943642d3996ad81e136570a4

      - name: Deploy Manifests to EKS
        run: |
          kubectl apply -f backend/catalog-service/k8s/deployment.yaml
          kubectl apply -f frontend/k8s/ingress.yaml
          kubectl rollout restart deployment/catalog-service-deployment
